### ISSUE TITLE
Matching Requests for Real Estate Extension Issue

### ISSUE THREAD

**Issue by fioreidr** [espocrm/ext-real-estate#11]
**Matching Requests does not recognize or match with the Location.**

There is a big problem with Matching Requests. Where you create a request it will match perfectly and display all the properties that match with that request. If you go to the Properties you can see that the Matching Requests to that particular property do not have the same Location as the property. All the other fields match but the Location field. The Matching Request list under the matching Property do not even display the Location on the list until the request is opened.  

**Reproduce Behavior**
1. Create a Property
2. Create a Request with the same requirements as the Property(bedroom, price, property type) but chose different location from the property
3. Go to the Property and scroll down to Matching Requests and you will see it matches to the incorrect Request.

**Expected behavior**
Matching Requests must have or contain the Properties Location. Requests should not match with Properties that don't have that Location. 

**EspoCRM version**
EspoCRM version 7.2.4, Real Estate Extension Version 1.6.0

More detiails in the video: 

https://user-images.githubusercontent.com/116065198/196381992-897fa29b-f0f4-4c39-a840-d0cf70dadcbb.mp4

**Comment by yurikuzn** [comment]
Fix: https://github.com/espocrm/ext-real-estate/commit/c7fcd52576087d4e845dfe67abcf22f6bd2ebc42

Will be released soon.
