### ISSUE TITLE
Espocrm 6.0.0 and real-estate extention 1.4.0 upgrade failed

### ISSUE THREAD

**Issue by sergpr** [espocrm/ext-real-estate#3]
**I can't update espocrm to new version 6.0.0 because of error:**

_Error: EspoCRM 6.0.0 is not compatible with Real Estate extension of a version lower than 1.4.0. Please upgrade the extension or uninstall it. Then run the upgrade command again._

**Also, I can't update real estate extention because of error:**

_Your EspoCRM version (5.9.4) is not supported. Required version: >=6.0.0._

I am confused how to update correctly without uninstalling extention.
Thanks.

**Comment by yurikuzn** [comment]
1. Uninstall the extension.
2. Upgrade.
3. Install an extension (1.4.0).

**Comment by sergpr** [comment]
Will it not affect my existing extention settings?

**Comment by yurikuzn** [comment]
Should not.  This script will be executed on uninstallation: https://github.com/espocrm/ext-real-estate/blob/master/src/scripts/AfterUninstall.php. So the worst case scenario is loosing tab list, default dashboard, and quick create list.

**Comment by sergpr** [comment]
Everything fine, thank you very much!

**Comment by bforc** [comment]
Sorry to hear about the EspoCRM 6.0.0 and Real Estate Extension 1.4.0 upgrade issue! For reliable property listing solutions, consider exploring [NY State MLS](https://nystatemls.com/). It’s a robust platform for real estate professionals, ensuring seamless listings without the hassle of technical glitches. Let me know if you need help troubleshooting!
